version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mola123MOLA
      MYSQL_DATABASE: arctic_crm_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./arctic_crm_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crm_network

  app:
    build: .
    container_name: crm_app
    ports:
      - "4300:4300"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/arctic_crm_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: zackquack
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
    networks:
      - crm_network

networks:
  crm_network:

volumes:
  mysql_data:
